%YAML:1.0

# ROS topics
color_topic: "/d455/color/image_raw"
depth_topic: "/d455/aligned_depth_to_color/image_raw"
infra1_topic: "/camera/camera/infra1/image_rect_raw/compressed"
infra2_topic: "/camera/camera/infra2/image_rect_raw/compressed"

color_info_topic: "/d455/color/camera_info"
infra1_info_topic: "/camera/camera/infra1/camera_info"
infra2_info_topic: "/camera/camera/infra2/camera_info"

# SAVE_IMG -> 0; not save & 1; save (.jpg) 
save_img: 1

# Publish Synced Images -> 0 (false) / 1 (true)
publish_synced_imgs: 1

# To set time difference
diff_threshold: 0.25

# Sync GT time with ROSBAG img -> 0 (false) / 1 (true)
sync_gt_time: 1

# Setting Closing time btw cur Img and GT Img
sim_threshold: 0.01

# GT pose path
gt_path: "/workspace/dataset/ar_table_dataset/groundtruth/table_01.txt"
